# Basics of Python
In this introductory tutorial, we will go through some of the basic concepts of Python Programming Language. This is by no means a complete course on Python, but rather a broad overlook at it's various utilities and flavours.

This notebook introduces the basics of Python programming, focusing on syntax, basic operations, data types, functions etc. and try certain applications catered towards weather and climate data. The contents of this notebook is a compilation of various tutuorials and open-source materials on the web.

## Basic syntax and data types

The core of any object-oriented language are its objects. In Python _everything_ is an object, from a function to a class to a variable. The simplest object is, in fact, a **variable**. Let's define the first variable here, and print its type.

In [1]:
x = 2
print(type(x))

<class 'int'>


We've taken a few steps so far. To begin, we created a variable named x and assigned it the value 2. Next, we used the `print` function to display the type of `x`. The print function can accept one or more inputs and displays the values of variables. You might have also observed that `type` is another function we used, which determines and returns the data type of the variable given to it.

There are other types of variables, such as strings, floats, and booleans. Let's see a few examples of these.

In [2]:
# Variables and Data Types
temperature = 22.5  # float
city = 'New York'   # string
is_sunny = True     # boolean

print(f'Temperature: {temperature}°C, City: {city}, Sunny: {is_sunny}')

Temperature: 22.5°C, City: New York, Sunny: True


The `#` symbol in Python marks the beginning of a **comment**. Comments serve as explanatory notes within the code, intended for the programmer and other readers. Python doesn't execute these lines - it simply ignores them. 

Developers use comments to:
- Clarify their code's purpose and functionality
- Make the code easier to understand and maintain
- Provide context or explanations for complex logic
- Temporarily disable certain parts of the code for testing

**Note:** Good commenting practices can significantly improve code readability and collaboration among developers.

### Basic Operators

Python offers various **operators** for manipulating variables. These operators follow a left-to-right evaluation order and adhere to the "PEMDAS" rule. Here's a brief overview of some common operators:

1. **Assignment operator**: `=`
   - Assigns a value to a variable
   - Example: `x = 5`

2. **Equality operator**: `==`
   - Checks if two values are equal
   - Example: `if x == 5:`

3. **Arithmetic operators**:
   - Addition: `+`
   - Subtraction: `-`
   - Multiplication: `*`
   - Division: `/`
   - Exponentiation: `**`

Let's apply these operators to convert temperature from Fahrenheit to Celsius. The mathematical formula is:

$$ C = 5(F - 32)/9 $$

We can implement this formula in Python code as follows:

In [5]:
F = 96  # it's quite hot out in America
C = 5 * (F - 32) / 9
print(f"It's equivalently hot in Europe: {C:.02f} degrees C!")

It's equivalently hot in Europe: 35.56 degrees C!


In the previous example, we've combined several concepts and introduced a new one: [f-strings](https://docs.python.org/3/tutorial/inputoutput.html). F-strings provide a powerful way to embed expressions inside string literals for formatting.

Key points about f-strings:

1. They allow us to insert variables directly into print statements.
2. The syntax `{C:.02f}` formats the `C` variable as a float with two decimal places.
3. F-strings can handle complex formatting, but even basic usage improves output readability.

**Note:** While the detailed formatting is optional, mastering f-strings can significantly enhance the professionalism of your output.

**Tip:** For a deeper understanding of f-strings and their capabilities, refer to the official Python documentation linked above.

Example usage:
```python
temperature_c = 25.4321
print(f"The temperature is {temperature_c:.2f}°C")
# Output: The temperature is 25.43°C

## Basic Python data structures

### Data Organization in Python

In scientific computing, efficient data organization is crucial. Python provides various data structures to help us organize and manage information effectively. These structures can contain other objects, allowing for complex data representations.

### Key Data Structures in Python

1. **Lists**: Ordered, mutable sequences
2. **Tuples**: Ordered, immutable sequences
3. **Dictionaries**: Key-value pairs
4. **Sets**: Unordered collections of unique elements
5. **Arrays**: Efficient storage for numerical data (via NumPy)
6. **DataFrames**: 2D labeled data structures (via Pandas)

Each of these structures has its own characteristics and use cases, making Python a versatile tool for scientific data manipulation and analysis.

In the following sections, we'll explore these data structures in detail, discussing their properties, use cases, and how to work with them effectively in scientific contexts.

### 1. Lists 

Lists are ordered, mutable sequences. They're versatile and commonly used for storing collections of related items.

In [6]:
# Example: List of experimental temperatures (in °C)
temperatures = [22.5, 23.1, 23.8, 22.9, 23.5]

print(f"Temperatures: {temperatures}")
print(f"Number of measurements: {len(temperatures)}")
print(f"Maximum temperature: {max(temperatures)}°C")

Temperatures: [22.5, 23.1, 23.8, 22.9, 23.5]
Number of measurements: 5
Maximum temperature: 23.8°C


Now, how do we access a number/element in a list? Python, like many (but not all!) programming languages, is "zero-indexed". That means the "first" element of the array is indexed by the number `0`. 

So, let's try and print few elements/entries from the list `temperatures`.

In [12]:
print(f"First Entry:  {temperatures[0]}")
print(f"Last Entry:  {temperatures[-1]}")
print(f"Also Last Entry:  {temperatures[4]}")

First Entry:  22.5
Last Entry:  23.5
Also Last Entry:  23.5


### 2. Tuples

Tuples are similar to lists but immutable. They're often used for fixed collections of data.

In [7]:
# Example: Representing a 3D coordinate
point = (2.5, 1.8, -3.2)

x, y, z = point  # Unpacking the tuple
print(f"The point is located at x={x}, y={y}, z={z}")

The point is located at x=2.5, y=1.8, z=-3.2


### 3. Dictionaries

Dictionaries store key-value pairs, allowing for efficient lookup and organization of data.

A list is an _ordered_ collection of items. A dictionary, or `dict`, is an unordered collection of data indexed by "keys". There are quite a few differences fundamentally between lists and dictionaries, but for now, we're going to focus on the most important two.
* Lists are _ordered_, dictionaries are _not ordered_
* Lists are accessed by integers starting from 0, dictionaries are indexed by keys of an arbitrary type

This second property especially makes them useful as lookup tables. For example, the following demonstrates how dictionaries are constructed and accessed.

In [13]:
# Example: Chemical elements and their atomic numbers
elements = {
    "Hydrogen": 1,
    "Helium": 2,
    "Lithium": 3,
    "Beryllium": 4
}

print(f"The atomic number of Helium is {elements['Helium']}")

# Adding a new element
elements["Carbon"] = 6
print(f"The new updated dictionary is: {elements}")

The atomic number of Helium is 2
The new updated dictionary is: {'Hydrogen': 1, 'Helium': 2, 'Lithium': 3, 'Beryllium': 4, 'Carbon': 6}


### 4. Sets

Sets are unordered collections of unique elements, useful for removing duplicates and set operations.

In [9]:
# Example: Unique species observed in an ecosystem
species_day1 = {"Wolf", "Fox", "Bear", "Rabbit"}
species_day2 = {"Fox", "Rabbit", "Deer", "Owl"}

all_species = species_day1.union(species_day2)
common_species = species_day1.intersection(species_day2)

print(f"All observed species: {all_species}")
print(f"Species observed on both days: {common_species}")

All observed species: {'Fox', 'Wolf', 'Bear', 'Owl', 'Deer', 'Rabbit'}
Species observed on both days: {'Rabbit', 'Fox'}


### 5. Arrays (NumPy)

NumPy arrays are efficient for numerical computations and are the foundation of many scientific Python libraries.

In [10]:
import numpy as np

# Example: Creating and manipulating a 2D array of experimental data
data = np.array([
    [1.2, 2.3, 3.1],
    [4.5, 5.2, 6.8],
    [7.1, 8.9, 9.3]
])

print("Original data:")
print(data)

print("\nMean of each column:")
print(np.mean(data, axis=0))

print("\nSum of all elements:")
print(np.sum(data))

Original data:
[[1.2 2.3 3.1]
 [4.5 5.2 6.8]
 [7.1 8.9 9.3]]

Mean of each column:
[4.26666667 5.46666667 6.4       ]

Sum of all elements:
48.400000000000006


### 6. DataFrames (Pandas)

Pandas DataFrames are 2D labeled data structures, excellent for working with structured data like tables or time series.

In [11]:
import pandas as pd

# Example: Creating a DataFrame of climate data
data = {
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04'],
    'Temperature': [22.5, 23.1, 22.8, 23.5],
    'Humidity': [45, 47, 44, 46],
    'Pressure': [1012, 1010, 1013, 1014]
}

df = pd.DataFrame(data)
print(df)

# Calculate average temperature
avg_temp = df['Temperature'].mean()
print(f"\nAverage Temperature: {avg_temp:.2f}°C")

         Date  Temperature  Humidity  Pressure
0  2023-01-01         22.5        45      1012
1  2023-01-02         23.1        47      1010
2  2023-01-03         22.8        44      1013
3  2023-01-04         23.5        46      1014

Average Temperature: 22.98°C


### Control Structures
For more details, refer to the [Python documentation on control flow](https://docs.python.org/3/tutorial/controlflow.html).

**Control flow** allows you to create "branches" in your code, enabling different blocks of code to be executed based on specific conditions. The most commonly used control flow structures are **if/elif/else** statements and **for/while loops**. In this section, we'll explore these concepts with some illustrative examples.

Let's write a simple function to classify weather based on temperature.

In [21]:
# Function to classify weather
def classify_weather(temp):
    if temp >= 30:
        return 'Hot'
    elif temp >= 20 and temp < 30:
        return 'Warm'
    else:
        return 'Cold'

# Test the function
temperature = 22.5
weather = classify_weather(temperature)
print(f'The weather is {weather}.')

The weather is Warm.


This code defines a function called `classify_weather` that categorizes the weather based on temperature. The function takes a single argument, `temp`:

- If the temperature is greater than 30, it returns 'Hot'.
- If the temperature is greater than 20 but less than or equal to 30, it returns 'Warm'.
- For any other temperature (20 or below), it returns 'Cold'.

After defining the function, we test it by passing a temperature of 22.5°C to `classify_weather`. The function returns 'Warm', and this result is printed as: "The weather is Warm."


## Hands-on Exercise
Calculate the average temperature for the list of `temperatures` below and classify it using the `classify_weather` function.

In [22]:
# Example: List of daily temperatures (in °C)
temperatures = [22.5, 25.3, 20.8, 18.6, 30.0]
#average_temp = sum(temperatures) / len(temperatures)
#print(f'Average Temperature: {average_temp:.2f}°C')

# Classify the weather based on average temperature
#weather_type = classify_weather(average_temp)
#print(f'The weather is {weather_type}.')